apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-persistence-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: address
    networking.gke.io/managed-certificates: managed-cert-ui
    kubernetes.io/ingress.class: gce
spec:
  rules:
  - host: api-persistence.history-from-the-frontier.com
    http:
      paths:
      - path: /*
        pathType: ImplementationSpecific
        backend:
          service:
            name: api-persistence-service
            port:
              number: 8081