apiVersion: v1
kind: Secret
metadata:
  name: mongo-credentials
type: Opaque
data:
  MONGO_USERNAME: c3RldmVncmVnaGF0Y2g=
  MONGO_PASSWORD: TUhQR0s0czY1Tk9xZ1NpSEBzZXVzcjA1MTcyMDI0LjJsZWZpMno=
  MONGO_HOST: bW9uZ29kYi5uZXQv
