apiVersion: v1
kind: Service
metadata:
  name: persistence-service
spec:
  type: ClusterIP
  selector:
    app: persistence-service
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
