name: build-push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel semver
          pip install -r requirements.txt

      - name: Get latest tag
        id: version
        run: |
          git fetch --tags
          latest_tag=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
          if [ -z "$latest_tag" ]; then
            new_version="0.0.1"
          else
            new_version="$latest_tag"
            while git rev-parse --quiet --verify "refs/tags/${new_version}"; do
              echo "Tag ${new_version} already exists. Incrementing..."
              new_version=$(python -c "import semver; print(semver.bump_patch('${new_version}'))")
            done
          fi
          echo "NEW_VERSION=$new_version" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/persistence-service:${{ env.NEW_VERSION }} .
          docker tag ${{ secrets.DOCKER_USERNAME }}/persistence-service:${{ env.NEW_VERSION }} ${{ secrets.DOCKER_USERNAME }}/persistence-service:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/persistence-service:${{ env.NEW_VERSION }}
          docker push ${{ secrets.DOCKER_USERNAME }}/persistence-service:latest

      - name: Push new or updated tag
        if: success()
        run: |
          new_version="${{ env.NEW_VERSION }}"
          while git rev-parse --quiet --verify "refs/tags/${new_version}"; do
            new_version=$(python -c "import semver; print(semver.bump_patch('${new_version}'))")
          done
          echo "Creating new tag: ${new_version}"
          git tag "${new_version}"
          git push origin "${new_version}"