name: build-push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel semver
          pip install -r requirements.txt

      - name: Get latest version from Git tags and increment
        id: version
        run: |
          latest_tag=$(git describe --abbrev=0)
          if [ -z "$latest_tag" ]; then
            new_version="0.0.1"
          else
            new_version=$(python -c "import semver; print(semver.bump_patch('$latest_tag'))")
          fi
          echo "new_version=$new_version" >> $GITHUB_ENV
          echo "VERSION=$new_version" >> $GITHUB_ENV

      - name: Push new tag
        run: |
          git tag ${{ env.new_version }}
          git push origin ${{ env.new_version }}
